// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_X6lCG6_tvLw69Rsqh_M3LAS0XqUtNkM',
    appId: '1:711795676084:web:595144cca75aaedd0bd8e1',
    messagingSenderId: '711795676084',
    projectId: 'pipeplank',
    authDomain: 'pipeplank.firebaseapp.com',
    storageBucket: 'pipeplank.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmkJuPaU9FYX76fBuuVbbSECBacIKXMSU',
    appId: '1:711795676084:android:f45b071cdf26e3270bd8e1',
    messagingSenderId: '711795676084',
    projectId: 'pipeplank',
    storageBucket: 'pipeplank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9Nzma7N-aVqLHNHxNKUxe7BXLYy6iKQ',
    appId: '1:711795676084:ios:678f2ca8bdd608190bd8e1',
    messagingSenderId: '711795676084',
    projectId: 'pipeplank',
    storageBucket: 'pipeplank.appspot.com',
    iosClientId: '711795676084-p3454bguc5a9pb0obnor1767d6pp98f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9Nzma7N-aVqLHNHxNKUxe7BXLYy6iKQ',
    appId: '1:711795676084:ios:678f2ca8bdd608190bd8e1',
    messagingSenderId: '711795676084',
    projectId: 'pipeplank',
    storageBucket: 'pipeplank.appspot.com',
    iosClientId: '711795676084-p3454bguc5a9pb0obnor1767d6pp98f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
